<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.1
 */

/**
 * Database `piscator_jr_fishing_gear`
 */

/* `piscator_jr_fishing_gear`.`RODS` */
return array(
  array('ID' => '1','RD_ID' => 'R001','Makers_Name' => 'Hardy','Model' => 'Smuggler','Sub_Model' => '#6 Graphite Smuggler Deluxe','Size' => '8\' 21/2"','Approx_date' => 'c1970','Details' => 'Nice Smuggler with restored leather tube (nicely done). Internally bag is dirty and rod well used - o/w F+','Rcondition' => 'VG+','Serial' => 'Z1bk11h352','Date_Purchased' => '03/2004','Price_paid' => '500','Valuation' => '600','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '2','RD_ID' => 'R002','Makers_Name' => 'Powell','Model' => 'LTT 895-3','Sub_Model' => '3 pc 5wt','Size' => '8\' 9"','Approx_date' => 'c1990','Details' => 'Nice almost unused graphite 5wt Powell rod in orig green canvas tube. Nickel silver fittings and lovely light wood reel seat','Rcondition' => 'VF','Serial' => NULL,'Date_Purchased' => '10/2005','Price_paid' => '400','Valuation' => '400','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '3','RD_ID' => 'R003','Makers_Name' => 'Hardy','Model' => 'The Taupo','Sub_Model' => '#7','Size' => NULL,'Approx_date' => NULL,'Details' => NULL,'Rcondition' => NULL,'Serial' => 'H41346C','Date_Purchased' => '04/2005','Price_paid' => '800','Valuation' => '800','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '4','RD_ID' => 'R004','Makers_Name' => 'Composite Developments','Model' => 'G3','Sub_Model' => '2pc 10-12wt','Size' => '9\'','Approx_date' => 'c1990\'s','Details' => 'Original NZ made Heavy Duty graphite SWF rod built for marlin & tuna','Rcondition' => 'Mint in org CD navy bag','Serial' => '18039','Date_Purchased' => '03/2005','Price_paid' => '250','Valuation' => '250','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '5','RD_ID' => 'R005','Makers_Name' => 'W H Tisdall','Model' => 'The Allan Pye Rod','Sub_Model' => '2 pc Bombassa Regd 19864','Size' => '2.93m','Approx_date' => 'c1960','Details' => 'Original Tisdall split cane rod named after the original owner of Huka Lodge - Allan Pye, nickel silver reel seat fittings & 1st eye with agate insert. Ferrule plug intact.','Rcondition' => 'VG+, straight but with tip guide having fallen off. In orig Tisdall cloth bag','Serial' => '1171','Date_Purchased' => '06/2005','Price_paid' => '400','Valuation' => '400','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '6','RD_ID' => 'R006','Makers_Name' => 'Hardy','Model' => 'The New Zealand Tournament','Sub_Model' => NULL,'Size' => NULL,'Approx_date' => 'c1960','Details' => 'Original NZ rarity in excellent condition. All intact with spare tip & both male & female ferrule protectors, orig clth bag and in cloth covered Hardy aluminium tube. Also includes orig tool and optional extra nickel silver reel seat fittings','Rcondition' => 'VF+','Serial' => 'E37570','Date_Purchased' => '06/2006','Price_paid' => '1100','Valuation' => '1000','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '7','RD_ID' => 'R007','Makers_Name' => 'Seeley','Model' => 'No 2 Action','Sub_Model' => '3 pc 8oz','Size' => '9\' 6"','Approx_date' => 'c1960','Details' => 'Nice glass Seeley rod in good condition with orig cloth bag','Rcondition' => 'VG','Serial' => NULL,'Date_Purchased' => '03/2005','Price_paid' => '200','Valuation' => '200','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '8','RD_ID' => 'R008','Makers_Name' => 'The Twiss Rod','Model' => NULL,'Sub_Model' => NULL,'Size' => NULL,'Approx_date' => '1934','Details' => '"Hand made by HT & TGL Twiss from TiTree. HT used it for many years on the Maungatu and caught many fish on this rod, rod hand turned from 1" square pieces of Titree. Ti tree came from Cashmore\'s firewood yard in Newmaket"…this history written on cloth bag.  Amazing item!','Rcondition' => 'VG for age','Serial' => NULL,'Date_Purchased' => '11/2005','Price_paid' => '250','Valuation' => '1000','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '9','RD_ID' => 'R009','Makers_Name' => 'Hardy','Model' => 'The New Zealand Tournament','Sub_Model' => NULL,'Size' => NULL,'Approx_date' => 'c1950','Details' => 'Original NZ rarity in poor to average condition but all intact with spare tip (tip guide broken), orig clth bag and in aluminium tube (no name) and with nickel silver & brass reel seat fittings. All guides have agate inserts.','Rcondition' => 'Poor to average with badly corroded butt cap - but fully restorable.','Serial' => 'E5893','Date_Purchased' => '06/2006','Price_paid' => '400','Valuation' => '500','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '10','RD_ID' => 'R010','Makers_Name' => 'Hardy','Model' => 'The New Zealand Tournament','Sub_Model' => NULL,'Size' => NULL,'Approx_date' => 'c1950','Details' => 'Original NZ rarity in VG condition - all intact with all agate lined guides & spare tip with non-orig clth bag and with nickel silver reel seat fittings. All guides have agate inserts.Looks like butt may be a replacement as no s/n as would be typical','Rcondition' => 'VG','Serial' => NULL,'Date_Purchased' => '03/2005','Price_paid' => '500','Valuation' => '700','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '11','RD_ID' => 'R011','Makers_Name' => 'Tisdall','Model' => 'The M.H.T Personal Rod','Sub_Model' => NULL,'Size' => NULL,'Approx_date' => 'c1930','Details' => 'Original NZ rarity in VG condition - all intact with all agate stripping guide, orig Tisdall clth bag and with nickel silver reel seat fittings stamped Tisdall & numbered.','Rcondition' => 'VG','Serial' => 'B283','Date_Purchased' => '03/2005','Price_paid' => '250','Valuation' => '500','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '12','RD_ID' => 'R012','Makers_Name' => 'Lindop','Model' => 'Lindfly','Sub_Model' => NULL,'Size' => '8\'','Approx_date' => 'c1950','Details' => 'Manchester, UK','Rcondition' => 'VG','Serial' => NULL,'Date_Purchased' => '03/2005','Price_paid' => '200','Valuation' => '200','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '13','RD_ID' => 'R013','Makers_Name' => 'Thomas & Thomas','Model' => 'HS906-4','Sub_Model' => '4pc #6','Size' => '9\'','Approx_date' => 'c1995','Details' => 'Neat little 6wt T & T with wood insert reel seat and usual T&T quality fittings. In orig blue T&T aluminium tube & cloth bag','Rcondition' => 'VG+','Serial' => '115787','Date_Purchased' => '01/1995','Price_paid' => '500','Valuation' => '500','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '14','RD_ID' => 'R014','Makers_Name' => 'Thomas & Thomas','Model' => 'HS910S-4','Sub_Model' => '4pc #10','Size' => '9\'','Approx_date' => 'c1995','Details' => 'Neat used 10wt T & T with usual T&T quality fittings. In orig blue T&T aluminium tube & cloth bag','Rcondition' => 'VG','Serial' => '76-583','Date_Purchased' => '01/1995','Price_paid' => '600','Valuation' => '600','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '15','RD_ID' => 'R015','Makers_Name' => 'Thomas & Thomas','Model' => 'HS912S-4','Sub_Model' => '4pc #12','Size' => '9\'','Approx_date' => 'c1995','Details' => 'Neat used 12wt T & T with usual T&T quality fittings. In orig blue T&T aluminium tube & cloth bag','Rcondition' => 'VG','Serial' => NULL,'Date_Purchased' => '01/1995','Price_paid' => '700','Valuation' => '700','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '16','RD_ID' => 'R016','Makers_Name' => 'Thomas & Thomas','Model' => 'VE908S-3','Sub_Model' => '3pc #8','Size' => '9\'','Approx_date' => 'c2000','Details' => 'Neat used 8wt T & T with upgraded to titanium T&T quality fittings. In orig blue T&T aluminium tube & cloth bag. Demo rod for Tackle Specs','Rcondition' => 'Mint','Serial' => '49-349','Date_Purchased' => '01/1995','Price_paid' => '1000','Valuation' => '1000','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '17','RD_ID' => 'R017','Makers_Name' => 'Thomas & Thomas','Model' => 'HS864-2','Sub_Model' => '2pc #4','Size' => '8 1/2\'','Approx_date' => 'c2003','Details' => 'Neat v lightly used 4wt T & T with wood insert reel seat and usual T&T quality fittings. In orig blue T&T aluminium tube & cloth bag. Demo rod for Tackle Specs','Rcondition' => 'VF+','Serial' => NULL,'Date_Purchased' => '01/2005','Price_paid' => '400','Valuation' => '500','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '18','RD_ID' => 'R018','Makers_Name' => 'G Loomis','Model' => 'F10810','Sub_Model' => 'GL3 #10','Size' => NULL,'Approx_date' => 'c2002','Details' => 'ex David Gong. Build by DG for his own use - neat rod.','Rcondition' => 'VF+','Serial' => NULL,'Date_Purchased' => '01/2005','Price_paid' => '300','Valuation' => '300','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '19','RD_ID' => 'R019','Makers_Name' => 'G Loomis','Model' => NULL,'Sub_Model' => NULL,'Size' => NULL,'Approx_date' => 'c2002','Details' => 'ex David Gong. Build by DG for John Rae for salmon trolling in the Queen Charlottes  - neat rod.','Rcondition' => 'Mint','Serial' => NULL,'Date_Purchased' => '01/2005','Price_paid' => '400','Valuation' => '400','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '20','RD_ID' => 'R020','Makers_Name' => 'Lamiglass','Model' => 'G1308-T','Sub_Model' => '12-30lb','Size' => '8 1/2\'','Approx_date' => 'c2000','Details' => 'ex David Gong. Purchased for salmon trolling at Rivers Inlet, BC  - neat rod.','Rcondition' => 'Mint','Serial' => NULL,'Date_Purchased' => '01/2000','Price_paid' => '450','Valuation' => '450','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '21','RD_ID' => 'R021e','Makers_Name' => 'Hardy','Model' => 'The New Zealand Tournament','Sub_Model' => NULL,'Size' => NULL,'Approx_date' => 'c1950','Details' => 'Original NZ rarity in restored condition but all intact with spare tip (tip guide broken), orig clth bag and nickel silver & brass reel seat fittings.','Rcondition' => 'VF - poss sl "over restored" - unable to be positively identified','Serial' => '45019C','Date_Purchased' => '03/2003','Price_paid' => '500','Valuation' => '600','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '22','RD_ID' => 'R022','Makers_Name' => 'Sage','Model' => 'Z-Axis','Sub_Model' => '690-4 (6 wt 9\')','Size' => '9\'','Approx_date' => '2008','Details' => 'Nice rod - lightly used','Rcondition' => 'F+','Serial' => NULL,'Date_Purchased' => '01/2009','Price_paid' => '625','Valuation' => '600','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '23','RD_ID' => 'R023','Makers_Name' => 'Sage','Model' => 'Z-Axis','Sub_Model' => '486-4 (4 wt 8\' 6")','Size' => '8 1/2\'','Approx_date' => '2008','Details' => 'Nice rod - lightly used','Rcondition' => 'F+','Serial' => NULL,'Date_Purchased' => '01/2009','Price_paid' => '600','Valuation' => '600','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '24','RD_ID' => 'R025','Makers_Name' => 'Sage','Model' => 'Z-Axis','Sub_Model' => '5126-4 (5wt 12\' 6")','Size' => '12\' 6"','Approx_date' => '2009','Details' => 'Great spey rod!!!','Rcondition' => 'Mint in mint rod orig tube with warranty card','Serial' => NULL,'Date_Purchased' => '07/2009','Price_paid' => '1200','Valuation' => '1200','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '25','RD_ID' => 'R021','Makers_Name' => 'Hardy','Model' => '"Houghton"','Sub_Model' => 'Dry Fly','Size' => '11\'','Approx_date' => '1911','Details' => 'Beautiful Hardy rod in great condition  (polished brass fittings) - made for Tisdall, with bamboo tube containing 2 tips - all straight','Rcondition' => 'VF+','Serial' => 'A60702','Date_Purchased' => '08/2009','Price_paid' => '250','Valuation' => '1000','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '26','RD_ID' => 'R027','Makers_Name' => 'Sage','Model' => 'Z-Axis','Sub_Model' => '590-4 (5wt 9\')','Size' => '9\'','Approx_date' => '2008','Details' => 'Nice rod - lightly used','Rcondition' => 'VF+','Serial' => 'AB30013?','Date_Purchased' => '08/2009','Price_paid' => '450','Valuation' => '500','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '27','RD_ID' => 'R028','Makers_Name' => 'Sage','Model' => 'Z-Axis','Sub_Model' => '890-4 (8wt 9\')','Size' => '9\'','Approx_date' => '2008','Details' => 'Nice rod - lightly used','Rcondition' => 'VF+','Serial' => NULL,'Date_Purchased' => '07/2012','Price_paid' => '550','Valuation' => '550','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '28','RD_ID' => 'R029','Makers_Name' => 'Sage','Model' => 'Z-Axis','Sub_Model' => '6110-4 (6wt 11\' switch rod)','Size' => '11\'','Approx_date' => '2008','Details' => 'Nice rod - lightly used','Rcondition' => 'VF+','Serial' => 'AC45141','Date_Purchased' => '11/2011','Price_paid' => '600','Valuation' => '550','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '29','RD_ID' => 'R030','Makers_Name' => 'FT Williams','Model' => 'Combat','Sub_Model' => NULL,'Size' => '6\' 6"','Approx_date' => '1960','Details' => 'Mint condition - beautiful!','Rcondition' => 'Mint','Serial' => NULL,'Date_Purchased' => '06/2010','Price_paid' => '400','Valuation' => '500','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '30','RD_ID' => 'R031','Makers_Name' => 'Sage','Model' => 'Z-Axis','Sub_Model' => '790-4 (7wt 9\')','Size' => '9\'','Approx_date' => '2010','Details' => 'Nice rod - lightly used','Rcondition' => 'VF+','Serial' => 'AA69002','Date_Purchased' => '07/2013','Price_paid' => '410','Valuation' => '400','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '31','RD_ID' => 'R032','Makers_Name' => 'Sage','Model' => 'Xi3','Sub_Model' => '690-4','Size' => '6 wt','Approx_date' => '2015','Details' => 'Purchased new: in use','Rcondition' => 'Great condition','Serial' => NULL,'Date_Purchased' => '08/2015','Price_paid' => '500','Valuation' => '500','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '32','RD_ID' => 'R033','Makers_Name' => 'Sage','Model' => 'Xi3','Sub_Model' => '890-4','Size' => '8 wt','Approx_date' => '2015','Details' => 'Purchased new:in use','Rcondition' => 'VF','Serial' => NULL,'Date_Purchased' => '07/2015','Price_paid' => '500','Valuation' => '500','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '33','RD_ID' => 'R034','Makers_Name' => 'Sage','Model' => 'Salt','Sub_Model' => '790-4','Size' => '7wt','Approx_date' => '2016','Details' => 'Purchased new:in use','Rcondition' => 'VF','Serial' => NULL,'Date_Purchased' => '10/2015','Price_paid' => '500','Valuation' => '500','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '34','RD_ID' => 'R035','Makers_Name' => 'Sage','Model' => 'Xi2','Sub_Model' => '990-4','Size' => '9\'','Approx_date' => '2000','Details' => NULL,'Rcondition' => 'VF cond','Serial' => NULL,'Date_Purchased' => NULL,'Price_paid' => '500','Valuation' => '500','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '35','RD_ID' => 'R036','Makers_Name' => 'Hardy','Model' => 'Smuggler','Sub_Model' => 'De-Luxe','Size' => '8\' 2 1/2"','Approx_date' => '1960\'s','Details' => 'A nice 8\' 2/1/2" Hardy 6wt Smuggler in leather case. Handle dirty but o/w VF (case has been refurbished)','Rcondition' => 'VF - case has been refurbished','Serial' => 'IEJ97247','Date_Purchased' => '03/2015','Price_paid' => '200','Valuation' => '400','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '36','RD_ID' => 'RD037','Makers_Name' => NULL,'Model' => NULL,'Sub_Model' => NULL,'Size' => NULL,'Approx_date' => NULL,'Details' => NULL,'Rcondition' => NULL,'Serial' => NULL,'Date_Purchased' => NULL,'Price_paid' => NULL,'Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '37','RD_ID' => 'RD038','Makers_Name' => NULL,'Model' => NULL,'Sub_Model' => NULL,'Size' => NULL,'Approx_date' => NULL,'Details' => NULL,'Rcondition' => NULL,'Serial' => NULL,'Date_Purchased' => NULL,'Price_paid' => NULL,'Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '38','RD_ID' => 'RD039','Makers_Name' => NULL,'Model' => NULL,'Sub_Model' => NULL,'Size' => NULL,'Approx_date' => NULL,'Details' => NULL,'Rcondition' => NULL,'Serial' => NULL,'Date_Purchased' => NULL,'Price_paid' => NULL,'Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '39','RD_ID' => 'RD040','Makers_Name' => NULL,'Model' => NULL,'Sub_Model' => NULL,'Size' => NULL,'Approx_date' => NULL,'Details' => NULL,'Rcondition' => NULL,'Serial' => NULL,'Date_Purchased' => NULL,'Price_paid' => NULL,'Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL)
);
