<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.1
 */

/**
 * Database `piscator_jr_fishing_gear`
 */

/* `piscator_jr_fishing_gear`.`TACKLE_U` */
return array(
  array('ID' => '1','U_ID' => 'U001','Type' => 'Reel','Makers_Name' => 'Penn','Model' => 'International','Sub_Model' => '975','Size' => NULL,'Approx_date' => '2005','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => NULL,'Tcondition' => NULL,'SerialNo' => '2/15/2007','Date_Purchased' => '1900-11-15 00:00:00','Price_paid' => '320','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '2','U_ID' => 'U002','Type' => 'Reel','Makers_Name' => 'Shimano','Model' => 'TLD 20 2 Speed','Sub_Model' => 'Will Fish conversion','Size' => NULL,'Approx_date' => 'c1990\'s','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'A fantastic and expensive conversion to open spool access up','Details' => 'Mint in like Shimano neoprene cover','Tcondition' => NULL,'SerialNo' => '3/15/2006','Date_Purchased' => '1901-02-03 00:00:00','Price_paid' => '600','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '3','U_ID' => 'U003','Type' => 'Reel','Makers_Name' => 'Shimano','Model' => 'TLD 30 2 Speed','Sub_Model' => 'Will Fish conversion','Size' => NULL,'Approx_date' => 'c1990\'s','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'A fantastic and expensive conversion to open spool access up','Details' => 'Mint in like Shimano neoprene cover','Tcondition' => NULL,'SerialNo' => '3/15/2006','Date_Purchased' => '1901-02-03 00:00:00','Price_paid' => '600','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '4','U_ID' => 'U004','Type' => 'Reel','Makers_Name' => 'Penn','Model' => 'International','Sub_Model' => '12T','Size' => NULL,'Approx_date' => '1991','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Nice little 12T that has been 2-speeded by Cal Sheets','Details' => 'F','Tcondition' => 'H910276','SerialNo' => '5/15/1995','Date_Purchased' => '1902-09-26 00:00:00','Price_paid' => '700','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '5','U_ID' => 'U005','Type' => 'Reel','Makers_Name' => 'Penn','Model' => 'Spinfisher','Sub_Model' => '716Z','Size' => NULL,'Approx_date' => 'c1980\'s','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Vice reel in VG cond - a few marks & scrateches','Details' => 'VG','Tcondition' => NULL,'SerialNo' => '3/15/1995','Date_Purchased' => '1900-07-18 00:00:00','Price_paid' => '100','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '6','U_ID' => 'U006','Type' => 'Reel','Makers_Name' => 'Alvey','Model' => 'Saltwater Fly','Sub_Model' => NULL,'Size' => '4"','Approx_date' => 'c1990\'s','Foot' => 'Alloy','Handle' => 'Single xylonite','Tension_Regulator' => 'Nice reel in VF cond','Details' => 'VF','Tcondition' => NULL,'SerialNo' => '5/15/2005','Date_Purchased' => '1900-04-09 00:00:00','Price_paid' => '100','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '7','U_ID' => 'U007','Type' => 'Reel','Makers_Name' => 'Penn','Model' => '349','Sub_Model' => 'Master Mariner','Size' => NULL,'Approx_date' => 'c1980','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Average, well used condition','Details' => 'Average','Tcondition' => NULL,'SerialNo' => '3/15/1988','Date_Purchased' => '1900-09-06 00:00:00','Price_paid' => '50','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '8','U_ID' => 'U009','Type' => 'Reel','Makers_Name' => 'Abel','Model' => 'No 1','Sub_Model' => NULL,'Size' => NULL,'Approx_date' => '1990\'s','Foot' => 'Alloy','Handle' => 'Rosewood','Tension_Regulator' => 'Very nice Abel reel in custom blue colour','Details' => 'VF','Tcondition' => '3624','SerialNo' => '6/15/2004','Date_Purchased' => '1901-05-14 00:00:00','Price_paid' => '500','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '9','U_ID' => 'U010','Type' => 'Reel','Makers_Name' => 'Pro Gear','Model' => NULL,'Sub_Model' => NULL,'Size' => NULL,'Approx_date' => NULL,'Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Black anodised with reel clamps','Details' => 'A few small chips o/w VF','Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => '1901-02-03 00:00:00','Price_paid' => '400','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '10','U_ID' => 'U011','Type' => 'Reel','Makers_Name' => 'Accurate','Model' => 'Boss Twin Drag','Sub_Model' => '870','Size' => NULL,'Approx_date' => '2000','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Mint unused condition - with special order black round handle','Details' => 'Mint','Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => '1902-03-10 00:00:00','Price_paid' => '800','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '11','U_ID' => 'U012','Type' => 'Reel','Makers_Name' => 'Accurate','Model' => 'Boss Twin Drag','Sub_Model' => '270','Size' => NULL,'Approx_date' => '2000','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Mint unused condition','Details' => 'Mint','Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => '1901-11-30 00:00:00','Price_paid' => '700','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '12','U_ID' => 'U013','Type' => 'Reel','Makers_Name' => 'Pro Gear','Model' => NULL,'Sub_Model' => NULL,'Size' => NULL,'Approx_date' => '2000','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Gold anodised without reel clamps','Details' => 'Near mint','Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => '1901-02-03 00:00:00','Price_paid' => '400','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '13','U_ID' => 'U014','Type' => 'Reel','Makers_Name' => 'Accurate','Model' => 'Boss Twin Drag','Sub_Model' => '870','Size' => NULL,'Approx_date' => '2000','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Mint unused condition','Details' => 'Mint','Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => '1902-01-19 00:00:00','Price_paid' => '750','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '14','U_ID' => 'U015','Type' => 'Reel','Makers_Name' => 'Shimano','Model' => 'Tiagra','Sub_Model' => '50','Size' => NULL,'Approx_date' => '2007','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Spooled 50lb Black Magic IGFA','Details' => 'Mint','Tcondition' => '#TI 88024','SerialNo' => '12/23/2007','Date_Purchased' => '1902-06-18 00:00:00','Price_paid' => '900','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '15','U_ID' => 'U016','Type' => 'Reel','Makers_Name' => 'Shimano','Model' => 'TLD','Sub_Model' => '30','Size' => NULL,'Approx_date' => '2004','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Spooled 50lb PowerPro','Details' => 'VF','Tcondition' => '100898','SerialNo' => '1/15/2004','Date_Purchased' => '1900-10-26 00:00:00','Price_paid' => '300','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '16','U_ID' => 'U017','Type' => 'Reel','Makers_Name' => 'Shimano','Model' => 'TLD','Sub_Model' => '20','Size' => NULL,'Approx_date' => '1998','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Spooled 30lb PowerPro','Details' => 'VG','Tcondition' => '22883','SerialNo' => '1/15/1998','Date_Purchased' => '1900-07-18 00:00:00','Price_paid' => '200','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '17','U_ID' => 'U018','Type' => 'Reel','Makers_Name' => 'Abel','Model' => 'TR 2','Sub_Model' => NULL,'Size' => '3"','Approx_date' => '2000','Foot' => NULL,'Handle' => 'Rosewood','Tension_Regulator' => 'Mint unused with black pouch and warranty card - "clown" anodising','Details' => 'Mint','Tcondition' => NULL,'SerialNo' => '9/15/2008','Date_Purchased' => '1901-03-25 00:00:00','Price_paid' => '450','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '18','U_ID' => 'U019','Type' => 'Reel','Makers_Name' => 'Pro Gear','Model' => '545','Sub_Model' => NULL,'Size' => NULL,'Approx_date' => '2000','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Blue anodised without reel clamps','Details' => 'VG','Tcondition' => NULL,'SerialNo' => '3/15/2000','Date_Purchased' => '1901-02-03 00:00:00','Price_paid' => '400','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '19','U_ID' => 'U020','Type' => 'Reel','Makers_Name' => 'Tica','Model' => 'Sculptor','Sub_Model' => 'SL100','Size' => NULL,'Approx_date' => '2007','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'New Tica baitcasting reel in firted neoprene case','Details' => 'Mint','Tcondition' => NULL,'SerialNo' => '12/15/2007','Date_Purchased' => '1900-07-18 00:00:00','Price_paid' => '200','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '20','U_ID' => 'U021','Type' => 'Reel','Makers_Name' => 'Hatch','Model' => 'Monsoon','Sub_Model' => 'Green','Size' => '3 Plus','Approx_date' => '2008','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Green 3 Plus  reel in red neoprene pouch','Tcondition' => 'Orignally came with U49 spool','SerialNo' => NULL,'Date_Purchased' => '1902-09-26 00:00:00','Price_paid' => '1000','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '21','U_ID' => 'U022','Type' => 'Reel','Makers_Name' => 'Pro Gear','Model' => '251','Sub_Model' => NULL,'Size' => NULL,'Approx_date' => '2000','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Red anodised variant, very early Pro Gear from factory - spooled 30lb Power Pro','Details' => 'Used (a few chips on rims etc)','Tcondition' => NULL,'SerialNo' => '1/15/2000','Date_Purchased' => '1901-02-03 00:00:00','Price_paid' => '400','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '22','U_ID' => 'U023','Type' => 'Reel','Makers_Name' => 'Abel','Model' => 'No 2','Sub_Model' => NULL,'Size' => NULL,'Approx_date' => '2000','Foot' => NULL,'Handle' => 'Rosewood','Tension_Regulator' => 'Black anodized reel in mint cond','Details' => 'Mint','Tcondition' => NULL,'SerialNo' => '2/15/2008','Date_Purchased' => '1901-05-14 00:00:00','Price_paid' => '500','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '23','U_ID' => 'U024','Type' => 'Reel','Makers_Name' => 'Daiwa','Model' => 'TD Sol','Sub_Model' => '3000','Size' => NULL,'Approx_date' => '2007','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Nice Sol reel with spare spool','Details' => 'VG+','Tcondition' => NULL,'SerialNo' => '8/15/2009','Date_Purchased' => '1900-10-26 00:00:00','Price_paid' => '300','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '24','U_ID' => 'U025','Type' => 'Rod','Makers_Name' => 'Shimano','Model' => 'T-Curve - Ian Miller','Sub_Model' => 'Snapper','Size' => '2.18m','Approx_date' => '2007','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Nice Ian Miller T Curve rod','Details' => 'VG','Tcondition' => NULL,'SerialNo' => '8/15/2009','Date_Purchased' => '1900-10-26 00:00:00','Price_paid' => '300','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '25','U_ID' => 'U026','Type' => 'Reel','Makers_Name' => 'Daiwa','Model' => 'Saltiga','Sub_Model' => 'Z-4000','Size' => NULL,'Approx_date' => '2009','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Nice used reel','Details' => 'VG - normal use','Tcondition' => NULL,'SerialNo' => '9/15/2009','Date_Purchased' => '1901-11-30 00:00:00','Price_paid' => '700','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '26','U_ID' => 'U027','Type' => 'Reel','Makers_Name' => 'Daiwa','Model' => 'Saltiga','Sub_Model' => 'Z-6500 Expedition','Size' => NULL,'Approx_date' => '2009','Foot' => NULL,'Handle' => 'Replacement','Tension_Regulator' => 'Nice used 6500 with light wear','Details' => 'VG','Tcondition' => NULL,'SerialNo' => '11/15/2009','Date_Purchased' => '1902-03-10 00:00:00','Price_paid' => '800','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '27','U_ID' => 'U028','Type' => 'Reel','Makers_Name' => 'Hatch','Model' => 'Monsoon','Sub_Model' => 'Blue','Size' => '7 Plus','Approx_date' => '2009','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Blue 7 Plus reel in red neoprene pouch','Tcondition' => 'Orignally came with U43 spool','SerialNo' => NULL,'Date_Purchased' => '2009-06-18 00:00:00','Price_paid' => '1000','Valuation' => '1000','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '28','U_ID' => 'U029','Type' => 'Reel','Makers_Name' => 'Daiwa','Model' => 'Certate','Sub_Model' => '3500 HD','Size' => NULL,'Approx_date' => '2009','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => NULL,'Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => '1899-12-30 00:00:00','Price_paid' => '0','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '29','U_ID' => 'U030','Type' => 'Reel','Makers_Name' => 'Hatch','Model' => 'Monsoon','Sub_Model' => 'Red','Size' => '7 Plus','Approx_date' => '2010','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Red 7 Plus reel in red neoprene pouch','Tcondition' => 'Orignally came with U31 spool','SerialNo' => NULL,'Date_Purchased' => '2010-06-01 00:00:00','Price_paid' => '800','Valuation' => '800','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '30','U_ID' => 'U031','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Monsoon','Sub_Model' => 'Red MA','Size' => '7 Plus','Approx_date' => '2010','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Red 7 Plus MA Monsoon spool','Tcondition' => 'Orignally came with U30 reel','SerialNo' => NULL,'Date_Purchased' => '1899-12-30 00:00:00','Price_paid' => '0','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '31','U_ID' => 'U032','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Pulse','Sub_Model' => 'Red LA','Size' => '9 Plus','Approx_date' => '2010','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Red 9 Plus spool red neoprene pouch','Tcondition' => 'Orignally came with U42 reel','SerialNo' => NULL,'Date_Purchased' => '2010-06-01 00:00:00','Price_paid' => '0','Valuation' => '0','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '32','U_ID' => 'U033','Type' => 'Reel','Makers_Name' => 'Hatch','Model' => 'Monsoon','Sub_Model' => 'Green','Size' => '5 Plus','Approx_date' => '2010','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Green 5 Plus reel in black neoprene pouch','Tcondition' => 'Orignally came with U42 spool','SerialNo' => NULL,'Date_Purchased' => '2010-07-01 00:00:00','Price_paid' => '750','Valuation' => '600','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '33','U_ID' => 'U034','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Monsoon','Sub_Model' => 'Blue LA','Size' => '5 Plus','Approx_date' => '2010','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Blue LA 5 Plus Monsoon spool','Tcondition' => 'Orignally came with U33 reel','SerialNo' => NULL,'Date_Purchased' => '2010-07-01 00:00:00','Price_paid' => '400','Valuation' => '400','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '34','U_ID' => 'U035','Type' => 'Reel','Makers_Name' => 'Avet','Model' => 'SX 6/4','Sub_Model' => 'Silver','Size' => NULL,'Approx_date' => '2011','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Brand new 2 speed reel','Details' => 'Mint','Tcondition' => NULL,'SerialNo' => '1/15/2011','Date_Purchased' => '1901-02-03 00:00:00','Price_paid' => '400','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '35','U_ID' => 'U036','Type' => 'Reel','Makers_Name' => 'Shimano','Model' => 'Tiagra','Sub_Model' => '50','Size' => NULL,'Approx_date' => '2009','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Very good condition - with new ergonomic handle','Details' => 'VG+','Tcondition' => NULL,'SerialNo' => '2/15/2011','Date_Purchased' => '1901-05-14 00:00:00','Price_paid' => '500','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '36','U_ID' => 'U037','Type' => 'Reel','Makers_Name' => 'Billy Pate','Model' => 'Marlin','Sub_Model' => NULL,'Size' => '4 1/2"','Approx_date' => 'c1990','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => 'Very nice Billy Pate reel in early style engraving','Details' => 'Used but still in VG+ cond','Tcondition' => 'A472','SerialNo' => '12/15/1995','Date_Purchased' => '1901-05-14 00:00:00','Price_paid' => '400','Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '37','U_ID' => 'U038','Type' => 'Reel','Makers_Name' => 'Hayden','Model' => 'TFO SS','Sub_Model' => '1','Size' => '3 3/4"','Approx_date' => '2014','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Temple Fork Outfitters teamed up with famed Australian reel designer Terry Hayden to create a new reel that is designed to battle the strongest fish in the ocean. 

Machined from 6061 marine grade aluminum and Type III Hard Anodized, TFO\'s Hayden reels are built tough for a lifetime of service. Hard Anodization penetrates the base metal becoming an integral part of the material while building up on the surface creating a finish that is harder and more durable than those found on the most expensive reels. WF9F with 200yds 30lb dacron','Tcondition' => 'NIB','SerialNo' => NULL,'Date_Purchased' => '2014-11-01 00:00:00','Price_paid' => '260','Valuation' => '600','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '38','U_ID' => 'U039','Type' => 'Reel','Makers_Name' => 'Hayden','Model' => 'TFO SS','Sub_Model' => '1','Size' => '3 3/4"','Approx_date' => '2014','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Temple Fork Outfitters teamed up with famed Australian reel designer Terry Hayden to create a new reel that is designed to battle the strongest fish in the ocean. 

Machined from 6061 marine grade aluminum and Type III Hard Anodized, TFO\'s Hayden reels are built tough for a lifetime of service. Hard Anodization penetrates the base metal becoming an integral part of the material while building up on the surface creating a finish that is harder and more durable than those found on the most expensive reels. WF9F with 200yds 30lb dacron','Tcondition' => 'NIB','SerialNo' => NULL,'Date_Purchased' => '2014-11-01 00:00:00','Price_paid' => '260','Valuation' => '600','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '39','U_ID' => 'U041','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Finatic','Sub_Model' => 'Red MA','Size' => '9 Plus','Approx_date' => '2011','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Red MA 9 Plus Finatic spool','Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => '2011-06-01 00:00:00','Price_paid' => '600','Valuation' => '600','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '40','U_ID' => 'U042','Type' => 'Reel','Makers_Name' => 'Hatch','Model' => 'Pulse','Sub_Model' => 'Red LA','Size' => '9 Plus','Approx_date' => '2010','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Red 9 Plus reel in red neoprene pouch','Tcondition' => 'Orignally came with U32 spool','SerialNo' => NULL,'Date_Purchased' => '2010-06-01 00:00:00','Price_paid' => '1200','Valuation' => '1200','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '41','U_ID' => 'U043','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Monsoon','Sub_Model' => 'Blue LA','Size' => '7 Plus','Approx_date' => '2014','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Blue LA 7 Plus Monsoon spool in red neoprene pouch','Tcondition' => 'Came with U28','SerialNo' => NULL,'Date_Purchased' => '2011-07-01 00:00:00','Price_paid' => '0','Valuation' => '0','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '42','U_ID' => 'U044','Type' => 'Reel','Makers_Name' => 'Hatch','Model' => 'Finatic','Sub_Model' => 'Red','Size' => '5 Plus','Approx_date' => '2014','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Red 5 Plus reel in red neoprene pouch','Tcondition' => 'Comes with U45 spool','SerialNo' => NULL,'Date_Purchased' => '2015-10-01 00:00:00','Price_paid' => '900','Valuation' => '900','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '43','U_ID' => 'U045','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Finatic','Sub_Model' => 'Red LA','Size' => '5 Plus','Approx_date' => '2014','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Red LA 5 Plus Finatic spool','Tcondition' => 'Comes with U44 reel','SerialNo' => NULL,'Date_Purchased' => '2015-10-01 00:00:00','Price_paid' => '0','Valuation' => '0','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '44','U_ID' => 'U046','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Pulse','Sub_Model' => 'Red LA','Size' => '7 Plus','Approx_date' => '2010','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Red LA 7 Plus spool in red neoprene pouch','Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => '2010-07-01 00:00:00','Price_paid' => '500','Valuation' => '500','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '45','U_ID' => 'U047','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Finatic','Sub_Model' => 'Blue MA','Size' => '7 Plus','Approx_date' => '2014','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Blue MA 7 Plus spool in red neoprene pouch','Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => '2014-10-01 00:00:00','Price_paid' => '400','Valuation' => '400','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '46','U_ID' => 'U048','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Finatic','Sub_Model' => 'Red LA','Size' => '5 Plus','Approx_date' => '2010','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Red LA 5 Plus Finatic spool','Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => '2015-10-01 00:00:00','Price_paid' => '250','Valuation' => '250','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '47','U_ID' => 'U049','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Monsoon','Sub_Model' => 'Green LA','Size' => '3 Plus','Approx_date' => '2010','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Green 3 Plus LA spool','Tcondition' => 'Originally came with U21 reel','SerialNo' => NULL,'Date_Purchased' => '2010-07-01 00:00:00','Price_paid' => '0','Valuation' => '0','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '48','U_ID' => 'U050','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Monsoon','Sub_Model' => 'Green LA','Size' => '5 Plus','Approx_date' => '2010','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Green LA 5 Plus Monsoon spool','Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => NULL,'Price_paid' => '0','Valuation' => '0','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '49','U_ID' => 'U051','Type' => 'Reel','Makers_Name' => 'Hatch','Model' => 'Monsoon','Sub_Model' => 'Red','Size' => '7 Plus','Approx_date' => NULL,'Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Red LA 7 Plus in red neoprene pouch','Tcondition' => 'Originally came with U46 spool','SerialNo' => NULL,'Date_Purchased' => NULL,'Price_paid' => '0','Valuation' => '0','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '50','U_ID' => 'U052','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Finatic','Sub_Model' => 'Blue','Size' => '7 Plus','Approx_date' => NULL,'Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Blue MA 7 Plus spool in red neoprene pouch','Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => NULL,'Price_paid' => '0','Valuation' => '0','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '51','U_ID' => 'U053','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Monsoon','Sub_Model' => 'Blue','Size' => '7 Plus','Approx_date' => NULL,'Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Blue MA 7 Plus spool','Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => NULL,'Price_paid' => '0','Valuation' => '0','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '52','U_ID' => 'U054','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Finatic','Sub_Model' => 'Blue','Size' => '7 Plus','Approx_date' => NULL,'Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Blue LA 7 Plus reel in red neoprene pouch','Tcondition' => 'Originally came with U55 reel','SerialNo' => NULL,'Date_Purchased' => NULL,'Price_paid' => '0','Valuation' => '0','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '53','U_ID' => 'U055','Type' => 'Reel','Makers_Name' => 'Hatch','Model' => 'Finatic','Sub_Model' => 'Blue','Size' => '7 Plus','Approx_date' => '2017','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Blue MA 7 Plus reel in red neoprene pouch','Tcondition' => 'Originally came with U54 spool','SerialNo' => NULL,'Date_Purchased' => '2017-07-01 00:00:00','Price_paid' => '675','Valuation' => '0','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '54','U_ID' => 'U056','Type' => 'Spool','Makers_Name' => 'Hatch','Model' => 'Finatic','Sub_Model' => 'Red','Size' => '7 Plus','Approx_date' => NULL,'Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Nice Red MA 7 Plus spool','Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => NULL,'Price_paid' => '0','Valuation' => '0','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '55','U_ID' => 'U057','Type' => 'Reel','Makers_Name' => 'Daiwa','Model' => 'Exist','Sub_Model' => '3000','Size' => NULL,'Approx_date' => '2015','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Very nice Daiwa Exist 3000','Tcondition' => 'VF','SerialNo' => NULL,'Date_Purchased' => '2017-09-17 00:00:00','Price_paid' => '425','Valuation' => '500','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '56','U_ID' => 'U058','Type' => 'Reel','Makers_Name' => 'Daiwa','Model' => 'Exist','Sub_Model' => '3000','Size' => NULL,'Approx_date' => '2015','Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => 'Very nice Daiwa Exist 3000','Tcondition' => 'VF','SerialNo' => NULL,'Date_Purchased' => '2017-09-16 00:00:00','Price_paid' => '675','Valuation' => '500','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '57','U_ID' => 'U059','Type' => 'Reel','Makers_Name' => 'Billy Pate','Model' => 'Marlin','Sub_Model' => 'AR','Size' => '4 1/2"','Approx_date' => '1990','Foot' => 'Aluminium','Handle' => 'Ebonite','Tension_Regulator' => NULL,'Details' => 'Really nice Billy Pate "Marlin" reel loaded with 12wt floating line in original blue neoprene puch','Tcondition' => 'VF+','SerialNo' => NULL,'Date_Purchased' => '2019-12-01 00:00:00','Price_paid' => '450','Valuation' => '450','date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '58','U_ID' => 'U060','Type' => 'Reel','Makers_Name' => 'Hatch ','Model' => 'Finatic 3 Plus','Sub_Model' => 'Blue/silver','Size' => '3.25','Approx_date' => '	','Foot' => 'Aluminium','Handle' => 'Aluminium','Tension_Regulator' => 'Drag','Details' => 'Really nice Dark blue/silver Hatch 3 Plus with a 4 wt WF clear line','Tcondition' => 'Mint','SerialNo' => NULL,'Date_Purchased' => '11-01-2022','Price_paid' => '420.00','Valuation' => '600.00','date_sold' => '','sale_price' => '0.00','sold_to' => '','sold_to_email' => ''),
  array('ID' => '59','U_ID' => 'U061','Type' => 'Reel','Makers_Name' => 'Hatch','Model' => 'Finatic 4 Plus','Sub_Model' => 'Grey/black','Size' => '3.425','Approx_date' => '2019','Foot' => 'Aluminum','Handle' => 'Aluminum','Tension_Regulator' => 'Drag','Details' => 'A lovely special order Hatch 4 Plus in grey/black with backing. Comes with spare spool','Tcondition' => 'Mint','SerialNo' => NULL,'Date_Purchased' => '12-01-2022','Price_paid' => '730.00','Valuation' => '999','date_sold' => '','sale_price' => '0.00','sold_to' => '','sold_to_email' => ''),
  array('ID' => '60','U_ID' => 'U062','Type' => 'Reel','Makers_Name' => 'Nautilus','Model' => 'Monster','Sub_Model' => '','Size' => '12.5cm x 4.5cm ','Approx_date' => '2020','Foot' => 'Metal','Handle' => 'Black plastic','Tension_Regulator' => 'Disc drag','Details' => 'Nautilus NVG Monster Fly Reel with Airflo Tropical Punch floating 12 weight fly line $200 and 400 yards 68lb Hatch backing cost $300. Ideal for GT\'s, Sails, Yellowfin, Marlin. Probably the ultimate 12 weight fly reel in the world with insane mega drag. Unused, unmarked brand new condition. Over $2000 retail. Comes with Nautilus neoprene bag. This reel is right hand wind only, cannot be changed over to left hand wind. S/N L2839','Tcondition' => 'Mint in original neoprene cover','SerialNo' => NULL,'Date_Purchased' => '02/2022','Price_paid' => '1100.00','Valuation' => '1100.00','date_sold' => '','sale_price' => '','sold_to' => '','sold_to_email' => ''),
  array('ID' => '61','U_ID' => 'U063','Type' => 'Rod','Makers_Name' => 'Scott','Model' => 'Meridian','Sub_Model' => '12 weight','Size' => '9\'foot','Approx_date' => '2020','Foot' => '','Handle' => '','Tension_Regulator' => '','Details' => 'Scott Meridian 12 Weight Saltwater Fly Rod in excellent unused condition, perfect for sails, GT, Marlin, yellowfin, etc. Its been cast a few times but not used. $1600 new. Bargain for someone.','Tcondition' => 'Unused in tube','SerialNo' => NULL,'Date_Purchased' => '02/2022','Price_paid' => '600.00','Valuation' => '700.00','date_sold' => '','sale_price' => '','sold_to' => '','sold_to_email' => ''),
  array('ID' => '63','U_ID' => 'U064','Type' => 'Rod','Makers_Name' => 'Douglas','Model' => 'Upstream','Sub_Model' => 'Plus','Size' => '5wt','Approx_date' => '2020','Foot' => '','Handle' => '','Tension_Regulator' => '','Details' => 'Douglas Upstream Plus 9ft 5 weight and an aluminium rod tube.
"The Douglas Upstream Fly Rod Series are very special rods. It’s just the right size, with just the right flex. If you need to protect light tippets, if you’re casting the whole line or short distances, if you’re fishing to spooky trout where delicacy is required, if you need precise cast between 20 and 70 feet, these rods can get it all done. The Upstream Plus Fly Rods are a casters dream. The time and effort spent fighting with your rods to make the right cast is a thing of the past".','Tcondition' => 'The rod is in excellent condition.','SerialNo' => NULL,'Date_Purchased' => '02/2022','Price_paid' => '415.00','Valuation' => '420.00','date_sold' => '','sale_price' => '','sold_to' => '','sold_to_email' => ''),
  array('ID' => '64','U_ID' => 'U065','Type' => 'Reel','Makers_Name' => 'Shimano','Model' => 'Talica','Sub_Model' => '50II','Size' => '','Approx_date' => '2018','Foot' => '','Handle' => '','Tension_Regulator' => '','Details' => 'Nice 50II in great condition with Shimano Tiagra Ultra 50/80 rod in case','Tcondition' => 'VG+
S/N: 51128','SerialNo' => NULL,'Date_Purchased' => '12/2022','Price_paid' => '600.00','Valuation' => '600.00','date_sold' => '','sale_price' => '','sold_to' => '','sold_to_email' => ''),
  array('ID' => '65','U_ID' => 'U066','Type' => 'Reel','Makers_Name' => 'Shimano','Model' => 'Talica','Sub_Model' => '50II','Size' => '','Approx_date' => '2018','Foot' => '','Handle' => '','Tension_Regulator' => '','Details' => 'Nice 50II in great condition with Shimano Tiagra Ultra 50/80 rod in case','Tcondition' => 'VG+
S/N: 57271','SerialNo' => NULL,'Date_Purchased' => '12/2022','Price_paid' => '600.00','Valuation' => '600.00','date_sold' => '','sale_price' => '','sold_to' => '','sold_to_email' => ''),
  array('ID' => '66','U_ID' => 'U067','Type' => 'Reel','Makers_Name' => 'Shimano','Model' => 'Talica','Sub_Model' => '5oII','Size' => '','Approx_date' => '2018','Foot' => '','Handle' => '','Tension_Regulator' => '','Details' => 'Nice 50II in great condition with Shimano Tiagra Ultra 50/80 rod in case','Tcondition' => 'VG+
S/N: 56505','SerialNo' => NULL,'Date_Purchased' => '12/2022','Price_paid' => '600.00','Valuation' => '600.00','date_sold' => '','sale_price' => '','sold_to' => '','sold_to_email' => ''),
  array('ID' => '67','U_ID' => 'U068','Type' => 'Reel','Makers_Name' => 'Hatch','Model' => '4 Plus','Sub_Model' => '','Size' => '','Approx_date' => '2015','Foot' => 'Aluminum','Handle' => 'Aluminum','Tension_Regulator' => 'Aluminum','Details' => 'A nice 4 Plus reel in case with tool (in box). Looks like a 4 or 5wt RIO Gold line inclided','Tcondition' => 'VF+','SerialNo' => NULL,'Date_Purchased' => '15-08-2023','Price_paid' => '400.00','Valuation' => '400.00','date_sold' => '','sale_price' => '0.00','sold_to' => '','sold_to_email' => ''),
  array('ID' => '68','U_ID' => 'U069','Type' => 'other','Makers_Name' => 'Abel','Model' => 'Pliers','Sub_Model' => '','Size' => '15cm','Approx_date' => '1980','Foot' => '','Handle' => '','Tension_Regulator' => '','Details' => 'A lovely pair of small ABEL pliers in BLUEFIN colour...in great condition with matching ABEL leather pouch and ABEL retainer strap','Tcondition' => 'VR+','SerialNo' => NULL,'Date_Purchased' => '01-06-2024','Price_paid' => '400.00','Valuation' => '750.00','date_sold' => '','sale_price' => '0.00','sold_to' => '','sold_to_email' => ''),
  array('ID' => '70','U_ID' => 'U070','Type' => NULL,'Makers_Name' => NULL,'Model' => NULL,'Sub_Model' => NULL,'Size' => NULL,'Approx_date' => NULL,'Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => NULL,'Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => NULL,'Price_paid' => NULL,'Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL),
  array('ID' => '71','U_ID' => 'U071','Type' => NULL,'Makers_Name' => NULL,'Model' => NULL,'Sub_Model' => NULL,'Size' => NULL,'Approx_date' => NULL,'Foot' => NULL,'Handle' => NULL,'Tension_Regulator' => NULL,'Details' => NULL,'Tcondition' => NULL,'SerialNo' => NULL,'Date_Purchased' => NULL,'Price_paid' => NULL,'Valuation' => NULL,'date_sold' => NULL,'sale_price' => NULL,'sold_to' => NULL,'sold_to_email' => NULL)
);
